---
- name: devops_playbook with ansible
  hosts: dev-servers
  tasks:
    - name: Run nexus container
      command: docker start nexus
      ignore_errors: yes
    - name: Run sonarQube container
      command: docker start 1ddc95ed56f4
      ignore_errors: yes
    - name: Run prometheus container
      command: docker start prometheus
      ignore_errors: yes
    - name: Run grafana container
      command: docker start grafana
      ignore_errors: yes
