---
- name: ansible_playbook
  hosts: all
  remote_user: vagrant
  become: true
  tasks:
    - name: Start  Prometheus Container
      command: docker start 781fcd2a414c
      ignore_errors: yes
    - name: Start Grafana Container
      command: docker start fbf38caf562b
      ignore_errors: yes
    - name: Start Grafana Container
      command: docker start ce7ec17c2da0
      ignore_errors: yes
    - name: Start Nexus Container
      command: docker start d47a7e7666c7
      ignore_errors: yes




