---
- name: sample_book
  hosts: dev-servers
  remote_user: root
  become: true
  tasks:
    - name: Run nexus container
      command: docker start 679d0f2504c3
      ignore_errors: yes
    - name: Run sonarQube contanier
      command: docker start 252f02bd5326
      ignore_errors: yes
    - name: Run prometheus container
      command: docker start 84f46adf3a26
      ignore_errors: yes
    - name: Run grafana container
      command: docker start e459ec42aaf5
      ignore_errors: yes
