---
- name: sample_book
  hosts: dev-servers
  remote_user: root
  become: true
  tasks:
    - name: Run sonarQube contanier
      command: docker start 1ddc95ed56f4
      ignore_errors: yes
    - name: Run prometheus container
      command: docker start prometheus
      ignore_errors: yes
    - name: Run grafana container
      command: docker start grafana
      ignore_errors: yes