version: "3.3"
services:
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=devopsDB
      - MYSQL_USER=root
    ports:
      - 3306:3306

  docker-springboot-example:
    image: docker-springboot-example:latest
    ports:
      - 8089:8089
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      -   mysqldb