version: '3'
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysql4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devopsDB
    ports:
      - 3306:3306
    networks:
      - AppNet

  spring-boot:
    image: omardrissi/projectdevops3
    container_name: spring
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    networks:
      - AppNet
    restart: on-failure
  angular:
    image: omardrissi/angularproject2
    container_name: angular
    ports:
      - 80:80
    depends_on:
      - spring-boot
    networks:
      - AppNet

networks:
  AppNet:
