version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devopsDB
    ports:
      - 3306:3306
    networks:
      - AppNet

  spring-boot:
    image: omardrissi/projectdevops1
    container_name: spring
    ports:
      - 8089:80
    depends_on:
      - database
    networks:
      - AppNet
    restart: on-failure
  angular:
    image: omardrissi/angularproject
    container_name: angular
    ports:
      - 4200:80
    depends_on:
      - spring-boot
    networks:
      - AppNet

networks:
  AppNet:
